include $(THEOS)/makefiles/common.mk

TOOL_NAME = extrainst_
extrainst__FILES = extrainst_.mm csstore.cpp
extrainst__CODESIGN_FLAGS=-Sextrainst_.xml
extrainst__INSTALL_PATH=/DEBIAN/

include $(THEOS_MAKE_PATH)/tool.mk
